In [2]:
import numpy as np

#check numpy version
numpy_version = np.__version__
print(F"Numpy version:{numpy_version}")

#check available method
print(dir(np))

Numpy version:1.23.5
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__

### Creating int numpy arrays

In [3]:
# creating python list
python_list = [1,2,3,4,5]

# check the data type 
print('Type:', type(python_list))

print(python_list)

two_demensional_list = [[0,1,2], [3,4,5], [6,7,8]]
print(two_demensional_list)

# creating numpy (Numerical python) array from python list

numpy_array_from_list = np.array(python_list)
print('Type:', type(numpy_array_from_list))
print(numpy_array_from_list)


Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
Type: <class 'numpy.ndarray'>
[1 2 3 4 5]


### Creating float numpy arrays

In [ ]:
numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2)

### Creating boolean numpy arrays

In [ ]:
numpy_bool_array_ = np.array([0,-1,-1,0,0], dtype=bool)
print(numpy_bool_array_)

### Creating multidimensional array using numpy

In [5]:
two_demensional_list = [[1,2,3], [4,5,6], [7,8,9]]
numpy_two_dimensional_list = np.array(two_demensional_list)
print(numpy_two_dimensional_list)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Converting numpy array to list

In [6]:
np_to_list = numpy_array_from_list.tolist()
two_dimension_np_to_list = numpy_two_dimensional_list.tolist()
print(type(np_to_list))
print(type(two_dimension_np_to_list))
print('one dimensional array:', np_to_list)
print('two dimensional array:', two_dimension_np_to_list)

<class 'list'>
<class 'list'>
one dimensional array: [1, 2, 3, 4, 5]
two dimensional array: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### Creating numpy array from tuple

In [10]:
# Numpy array from tuple
# Creating tuple in Python
python_tuple = (1,2,3,4,5)
print('Type:', type(python_tuple))
print('python tuple:', python_tuple)

# create numpy array from tuple 
numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))
print('Numpy Array From Tuple:', numpy_array_from_tuple)


Type: <class 'tuple'>
python tuple: (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
Numpy Array From Tuple: [1 2 3 4 5]


### Shape of numpy array

In [13]:
nums= np.array([1,2,3,4,5])
print(nums)
print('shape of nums:', nums.shape)
print(two_demensional_list)
print('shape of numpy two demensional array', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[2,3,4,5], 
                                [4,3,2,5], 
                                [11,23,1,9]])
print('three by four array',three_by_four_array.shape)

[1 2 3 4 5]
shape of nums: (5,)
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
shape of numpy two demensional array (3, 3)
three by four array (3, 4)


### Data type of numpy array

In [9]:
int_list = [0,2,-1,4,-5]
int_array = np.array(int_list)
float_array = np.array(int_list, dtype=float)
bool_array = np.array([1,1,0,0,1], dtype=bool)

# print 
print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)
print(bool_array)
print(bool_array.dtype)

[ 0  2 -1  4 -5]
int32
[ 0.  2. -1.  4. -5.]
float64
[ True  True False False  True]
bool


### Size of a numpy array

In [14]:
mumpy_array_from_list = np.array([1,2,3,4,5])
numpy_two_dimensional_array_from_list = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])

print('The size:', numpy_array_from_list.size)
print('The size:', numpy_two_dimensional_array_from_list.size)

The size: 5
The size: 12


### Mathematical Operation using numpy

In [ ]:
print('original:', python_list)
numpy_array = np.array(python_list)
floor_division = numpy_array // 10
print(floor_division)

In [ ]:
# Converting int to string
print(numpy_array_from_list.astype('str'))


### Slicing Numpy array

In [ ]:
arr = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(arr)
print('second_row_first_column:', arr[::-1,::-1])

In [ ]:
print(arr)
arr[1,1] = 55
arr[1,2] = 88
arr[2,2] = 77
print(arr)

# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
my_zeros = np.zeros((3,3), dtype=int, order='C')
print(my_zeros)
my_ones = np.ones((3,3), dtype=int, order='C')
print(my_ones)

two = my_ones * 2
print(two)

first_shape  = np.array([[1,2,3], [4,5,6]])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

### Generating Random Numbers

In [ ]:
random_float = np.random.random()
print(random_float)

five_random_float = np.random.random(5)
print(five_random_float)

# init random

random_int = np.random.randint(0,10, size = 4)
print(random_int)


In [ ]:
random_int = np.random.randint(1,11, size=5)
random_int

In [13]:
random_int = np.random.randint(1,11, size=(3,2))
random_int

array([[9, 2],
       [7, 2],
       [6, 9]])

### Numpy and Statistics

In [25]:
# Matrix 
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=int, order='C'))
four_by_four_matrix

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [15]:
np.asarray(four_by_four_matrix)[2] = 4
np.asarray(four_by_four_matrix)[0] = 9
four_by_four_matrix

matrix([[9, 9, 9, 9],
        [1, 1, 1, 1],
        [4, 4, 4, 4],
        [1, 1, 1, 1]])

In [ ]:
# Range
lst = range(1, 11, 1)
for i in lst:
    print(i)

In [18]:
lst = np.arange(1,11,1)
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
even_list = np.arange(2,11,1)
even_list

In [ ]:
odd_list = np.arange(1, 11, 2)
odd_list

In [6]:
# Horitzontal Stack
# Vertical Stack
np_list_one = np.array([1,2,3,4])
np_list_two = np.array([5,6,7,8])
np_list_three = np.hstack((np_list_one, np_list_two))
print('Horizontal Append:', np_list_three)
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))


Horizontal Append: [1 2 3 4 5 6 7 8]
Vertical Append: [[1 2 3 4]
 [5 6 7 8]]


In [27]:
# Matrix in numpy
four_by_four_matrix = np.matrix(np.ones((4,4), dtype=int))
four_by_four_matrix


matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

### Creating sequence of numbers using linspace

In [33]:
# numpy.linspace()
# numpy.logspace() in Python with Example
# For instance, it can be used to create 10 values from 1 to 5 evenly spaced.

np.linspace(1.0, 5.0, num=10, endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [34]:
# indexing and Slicing NumPy Arrays in Python
np_list = np.array([(1,2,3), (4,5,6)])
np_list

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
print('First row:', np_list[0])
print('Second row:', np_list[1])

First row: [1 2 3]
Second row: [4 5 6]


In [39]:
print('First colunm:', np_list[:,0])
print('Second colunm:', np_list[:,1])
print('Third colunm:', np_list[:,2])


First colunm: [1 4]
Second colunm: [2 5]
Third colunm: [3 6]


In [2]:
import numpy as np
numpy_array_from_list = np.array([1, 2, 3, 4, 5])

# Addition 
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)

# Subtraction 
ten_minus_original = numpy_array_from_list  - 10
print(ten_minus_original)

# Multiplication
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

# Division
ten_divide_original = numpy_array_from_list / 10
print(ten_divide_original)

# Modulus: Finding the remainder
mod_original = numpy_array_from_list % 3
print(mod_original)

# Exponential is finding some number the power of another
two_expon_original = numpy_array_from_list  ** 2
print(two_expon_original)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]
[1 2 0 1 2]
[ 1  4  9 16 25]
